title:              Alitrack ML
email:              
description:        Machine Learning
author:             Steven Lee
baseurl:            ""
url:                "https://alitrack.github.io/"

# Social Profiles
twitter_username: alitrack
github_username:  alitrack  
facebook_username:  
instagram_username:  
linkedin_username: witwall

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-180758632-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5